//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproj
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int job_id { get; set; }
        public string job_title { get; set; }
        public string jb_des { get; set; }
        public string jb_skills { get; set; }
        public int comp_id { get; set; }
        public System.DateTime closing_date { get; set; }
        public string status { get; set; }
    }
}
